-- Ürünler tablosunu genişletmek için migrasyon scripti
-- Cari sistemindeki detaylara uyum sağlamak için yeni kolonlar ekleniyor.

ALTER TABLE urunler ADD COLUMN IF NOT EXISTS urun_tipi VARCHAR(50) DEFAULT 'Ürün';
ALTER TABLE urunler ADD COLUMN IF NOT EXISTS urun_cinsi VARCHAR(100) DEFAULT '';
ALTER TABLE urunler ADD COLUMN IF NOT EXISTS urun_kodu VARCHAR(100) DEFAULT '';
ALTER TABLE urunler ADD COLUMN IF NOT EXISTS urun_barkodu VARCHAR(100) DEFAULT '';
ALTER TABLE urunler ADD COLUMN IF NOT EXISTS alis_fiyati DECIMAL(15, 2) DEFAULT 0;
ALTER TABLE urunler ADD COLUMN IF NOT EXISTS satis_fiyati DECIMAL(15, 2) DEFAULT 0;
ALTER TABLE urunler ADD COLUMN IF NOT EXISTS alis_kdv_dahil BOOLEAN DEFAULT FALSE;
ALTER TABLE urunler ADD COLUMN IF NOT EXISTS satis_kdv_dahil BOOLEAN DEFAULT FALSE;
ALTER TABLE urunler ADD COLUMN IF NOT EXISTS kdv_orani INTEGER DEFAULT 20;
ALTER TABLE urunler ADD COLUMN IF NOT EXISTS otv_orani INTEGER DEFAULT 0;
ALTER TABLE urunler ADD COLUMN IF NOT EXISTS oiv_orani INTEGER DEFAULT 0;
ALTER TABLE urunler ADD COLUMN IF NOT EXISTS stok_takibi BOOLEAN DEFAULT TRUE;
ALTER TABLE urunler ADD COLUMN IF NOT EXISTS stok_uyari_limiti DECIMAL(15, 2) DEFAULT 10;
